---
- name: Deploy benchmark client
  hosts: client
  become: yes
  roles:
    - {  role: geerlingguy.pip,
         become: yes,
         ignore_error: yes
         }
    - geerlingguy.docker
    - {  role: apt-common,
         become: yes,
         ignore_error: yes
         }
    - { role: Stouts.collectd,
        install_collectd: yes,
        become: yes, 
        collectd_use_git: no, 
        collectd_use_ppa: yes, 
        collectd_use_ppa_ci: no,
        collectd_use_ppa_latest: yes,
        collectd_use_ppa_minimal: yes,
        ignore_error: yes,
        collectd_logpath: '/var/log/collectd.log',
        collectd_csv_logdir: '/var/log/csv',
        collectd_fdqnlookup: true,
        collectd_intel_pmutools: no,
        collectd_intel_rdt: no,
        collectd_write_amqp: yes,
        collectd_numa_cpu_aggr: no,
        docker_stats: yes,
        # YUM SPECIFIC
        #collectd_config_file: '/etc/collectd.conf',
        #collectd_config_dir: '/etc/collectd.d/',
        # collectd_plugins_dir: '/usr/lib64/collectd',
        #collectd_sbin_path: '/usr/sbin'

        }
    #- { role: docvu.collectd-nvidia,
    #     collectd_nvidia_gpu: yes,
    #     become: yes,
    #     ignore_error: no,
    #     collectd_config_dir: '/etc/collectd.d',
    #     collectd_sbin_path: '/usr/sbin'
    #    }  

  tasks: 
    - name: "update the etc hosts for indices-manager"
      #become: yes
      sudo: yes
      lineinfile: 
        group: root
        line: "{{indices_manager_ip}} indices-manager"
        mode: 420
        owner: root
        path: /etc/hosts
        regexp: indices-manager
        state: present
  vars: 
    indices_manager_ip: x.x.x.x
