---
- name: Deploy benchmark server
  hosts: server
  become: yes
  roles:
    - { role: apt-common }
    - { role: mtchavez.influxdb, influxdb_admin_enabled: "true"}
    - { role: Stouts.grafana}
    - { role: influxdb.grafana}
    - { role: rabbitmq_config }
    # - { role: ansible-go }
    # - { role: go-collector }
    - { role: ansible-chronograf }
    - { role: docvu.pycollectdsubscriber }
  vars: 
    fecbench_master_ip: y.y.y.y